# Generated by Django 4.0.8 on 2022-10-25 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '0003_region_expert_alter_region_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='region',
            name='user',
        ),
        migrations.AddField(
            model_name='region',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
