# Generated by Django 4.0.8 on 2022-10-26 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '0006_remove_region_users_region_expert_region_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_expert': False, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
