# Generated by Django 4.0.8 on 2022-12-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_note_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
