# Generated by Django 4.1.2 on 2022-10-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='images_date',
        ),
        migrations.AddField(
            model_name='region',
            name='dates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
