# Generated by Django 4.0.8 on 2022-10-25 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '0004_remove_region_expert_remove_region_user_region_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='user',
        ),
        migrations.AddField(
            model_name='region',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
