# Generated by Django 4.0.8 on 2022-10-30 07:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '0007_alter_region_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='expert',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_expert': True, 'is_superuser': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert', to=settings.AUTH_USER_MODEL, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
