# Generated by Django 4.0.8 on 2022-12-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0009_alter_region_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='date_last_download',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='task_id',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
