# Generated by Django 4.0.8 on 2022-10-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_expert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='expert',
            new_name='user',
        ),
    ]
