# Generated by Django 4.0.8 on 2022-10-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user_role',
            field=models.CharField(choices=[('U', 'User'), ('E', 'Expert'), ('A', 'Admin')], default='U', max_length=1),
        ),
    ]
