# Generated by Django 4.0.8 on 2022-10-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='user_role',
            field=models.CharField(choices=[('U', 'User'), ('E', 'Expert'), ('A', 'Admin')], max_length=1),
        ),
    ]
