version: "3.9"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    restart: on-failure
    env_file:
      - .env
    networks:
      - main
    ports:
      - "5672:5672"

  celery_worker:
    container_name: celery_worker
    restart: on-failure
    command: celery -A config worker -l INFO --concurrency=4
    build:
      context: ./celery
    depends_on:
      - rabbitmq
    env_file:
      - .env
    networks:
      - main


networks:
  main:

volumes:
  db_data:
  geoserver_sedreh:
  geoserver_footprints_sedreh:
  geoserver_gwc_sedreh:
  geoserver_letsencrypt_sedreh:
  geoserver_fonts_sedreh:
  settings: